In [1]:
import numpy as np

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = 15

In [3]:
npArr = np.array(range(n-1,-1, -1))

In [4]:
npArr

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
npDiag = np.diag(npArr, k=0)

In [6]:
npDiag

array([[14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [7]:
sum(sum(npDiag))

105

А зачем вообще тут матрицы? 0_о  
Т.к. диагональная матрица — квадратная матрица, все элементы которой, стоящие вне главной диагонали, равны нулю, сумма каждой строки = элемент... 

In [8]:
sum([x for x in range(0,n)])

105

### Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3


In [9]:
a = np.array( [ 
    [4, 2, 1], 
    [1, 3, 0], 
    [0, 5, 4]
] )
b = np.array( [4, 12, -3] )

In [10]:
from numpy import linalg

In [11]:
c = linalg.solve(a,b)
c

array([ 0.46666667,  3.84444444, -5.55555556])

Проверка "по простому"

In [12]:
[
    (4 * c[0]) + (2 * c[1]) + (1 * c[2]),
    (1 * c[0]) + (3 * c[1]) + (0 * c[2]),
    (0 * c[0]) + (5 * c[1]) + (4 * c[2])
]

[4.0, 11.999999999999998, -3.0]

Ошибки округления? Как избежать?

In [13]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Упражнение из урока

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [14]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [15]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [16]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [17]:
def vectors_degree(a, b):
    return np.arccos( cosine(a,b) ) * 360 / 2 / np.pi

vectors_degrees = [vectors_degree(a, next_user_stats) for num, a in enumerate(users_stats)]
smallest_el = np.argmin(vectors_degrees)

vectors_degrees

[78.46304096718453,
 32.311533237423866,
 66.42182152179818,
 37.761243907035045,
 66.42182152179818,
 90.0,
 90.0,
 18.434948822922017,
 90.0,
 90.0]

In [18]:
print((
f"Наиболее похожий пользователь: №{smallest_el} (вектор - {users_stats[smallest_el]}).\n\
Угол между векторами: {vectors_degrees[smallest_el]:.2f}"
))

Наиболее похожий пользователь: №7 (вектор - [0 1 1 0 0 0]).
Угол между векторами: 18.43
